Models/ErrorViewModel.cs
namespace WeatherAspNet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ViewComponents/CityTemperatureViewComponent.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using WeatherAspNet.Models.ViewModels;
using WeatherAspNet.Services;

namespace WeatherAspNet.Models.ViewComponents
{
    [ViewComponent]
    public class CityTemperatureViewComponent : ViewComponent
    {
        private readonly IWeatherService _weatherService;
        private WeatherData weatherData;

        public CityTemperatureViewComponent(IWeatherService weatherService)
        {
            _weatherService = weatherService;
            weatherData = new WeatherData();
        }
        public async Task<IViewComponentResult> InvokeAsync(string newCityName)
        {
            string? cityName = Request.Cookies["LastCity"];
            if (cityName == null)
            {
                HttpContext.Response.Cookies.Delete("LastCity");

                CookieOptions cookieOptions = new CookieOptions()
                {
                    Expires = DateTime.Now.AddDays(1)
                };
                HttpContext.Response.Cookies.Append("LastCity", "Sofia", cookieOptions);
                cityName = "Sofia";
            }

            weatherData = await _weatherService.GetCity(newCityName);
            if (weatherData == null)
            {
                weatherData = await _weatherService.GetCity(cityName);
            }
            else
            {
                HttpContext.Response.Cookies.Delete("LastCity");

                CookieOptions cookieOptions = new CookieOptions()
                {
                    Expires = DateTime.Now.AddDays(1)
                };
                HttpContext.Response.Cookies.Append("LastCity", newCityName, cookieOptions);
            }
            CityTemperature city = new CityTemperature(weatherData);

            return await Task.FromResult((IViewComponentResult)View("CityTemperature", city));

        }
    }
}

Models/ViewComponents/TemperatureMapViewComponent.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using WeatherAspNet.Models.ViewModels;
using WeatherAspNet.Services;

namespace WeatherAspNet.Models.ViewComponents
{
    [ViewComponent]
    public class TemperatureMapViewComponent : ViewComponent
    {
        private readonly IWeatherService _weatherService;

        public TemperatureMapViewComponent(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("TemperatureMap"));
        }
    }
}

Models/ViewModels/CityTemperature.cs
namespace WeatherAspNet.Models.ViewModels
{
    public class CityTemperature
    {

        public CityTemperature(WeatherData weatherData)
        {
            CityName = weatherData.Name;
            CountryCode = weatherData.Sys.Country;
            CityTemp = weatherData.Main.TempCelsius;
            CityTempFeelsLike = weatherData.Main.Feels_Like - 273.15f;
            IconUrl = "https://openweathermap.org/img/wn/" + weatherData.Weather[0].Icon + ".png";

            Weather = new Weather();
            Weather.Main = weatherData.Weather[0].Main;
            Weather.Description = char.ToUpper(weatherData.Weather[0].Description[0]) + weatherData.Weather[0].Description.Substring(1);

            AirInfo = new AirInfo();
            AirInfo.Humidity = weatherData.Main.Humidity;
            AirInfo.WindSpeed = weatherData.Wind.Speed;
            AirInfo.Visibility = Math.Round(weatherData.Visibility / 1000.0, 2);
        }
        public string CityName { get; set; }
        public double CityTemp { get; set; }
        public string CountryCode { get; set; }
        public double CityTempFeelsLike { get; set; }
        public string IconUrl { get; set; }
        public Weather Weather { get; set; }
        public AirInfo AirInfo { get; set; }
    }
    public class Weather
    {
        public string Main { get; set; }
        public string Description { get; set; }
    }
    public class AirInfo
    {
        public double Visibility { get; set; }
        public int Humidity { get; set; }
        public float WindSpeed { get; set; }
    }
}

Models/WeatherData.cs
namespace WeatherAspNet.Models
{
    public class WeatherData
    {
        public Coord Coord { get; set; }
        public WeatherItem[] Weather { get; set; }
        public string Base { get; set; }
        public Main Main { get; set; }
        public int Visibility { get; set; }
        public Wind Wind { get; set; }
        public Clouds Clouds { get; set; }
        public long Dt { get; set; }
        public Sys Sys { get; set; }
        public int Timezone { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int Cod { get; set; }
    }

    public class Coord
    {
        public float Lon { get; set; }
        public float Lat { get; set; }
    }

    public class WeatherItem
    {
        public int Id { get; set; }
        public string Main { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
    }

    public class Main
    {
        public float Temp { get; set; }
        public float Feels_Like { get; set; }
        public float Temp_Min { get; set; }
        public float Temp_Max { get; set; }
        public int Pressure { get; set; }
        public int Humidity { get; set; }
        public int SeaLevel { get; set; }
        public int GrndLevel { get; set; }
        public float TempKf { get; set; }

        // Additional property to get temperature in Celsius
        public float TempCelsius => Temp - 273.15f;
    }

    public class Wind
    {
        public float Speed { get; set; }
        public int Deg { get; set; }
        public float Gust { get; set; }
    }

    public class Clouds
    {
        public int All { get; set; }
    }

    public class Sys
    {
        public int Type { get; set; }
        public int Id { get; set; }
        public string Country { get; set; }
        public long Sunrise { get; set; }
        public long Sunset { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using WeatherAspNet.Models;

namespace WeatherAspNet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        Response.Cookies.Delete("LastCity");

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherAspNet.Models;
using WeatherAspNet.Services;

namespace WeatherAspNet.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;
        public WeatherController(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }

        public IActionResult Forcast()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Forcast(string newCityName)
        {
            ViewData["NewCityName"] = newCityName;
            return View();

        }
        public async Task<JsonResult> Coordinates()
        {
            string? cityName = Request.Cookies["LastCity"];

            WeatherData city = await _weatherService.GetCity(cityName);
            JsonResult jsonResult = Json(city.Coord);
            
            return jsonResult;
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
    <a class="btn btn-success" asp-controller="Weather" asp-action="Forcast">Weather</a>

</div>

Views/Shared/Components/CityTemperature/CityTemperature.cshtml
@model WeatherAspNet.Models.ViewModels.CityTemperature

<div class="city-temp-container">
    <div>
        <span>@DateTime.Now</span>
        <h1>@Model.CityName, @Model.CountryCode</h1>
    </div>

    <div class="temperature-container">
        <div class="temp-and-icon">
            <img src="@Model.IconUrl" alt="@Model.IconUrl" />

            <span class="temperature-text">

                  @string.Format("{0:0}°C", Model.CityTemp)
            </span>
        </div>
        <hr class="line-break" />
        <div class="more-info">
            <p>Feels like: @string.Format("{0:0}°C", Model.CityTempFeelsLike), @Model.Weather.Description</p>

            <ul class="more-info-list ">
                <li>
                    Wind speed: @Model.AirInfo.WindSpeed ms/N
                </li>
                <li>
                    Humidity: @Model.AirInfo.Humidity%
                </li>
                <li>
                    Visibility: @Model.AirInfo.Visibility km
                </li>
            </ul>
        </div>
    </div>

</div>

Views/Shared/Components/TemperatureMap/TemperatureMap.cshtml
<div id="map"></div> 
    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherAspNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherAspNet.styles.css" asp-append-version="true" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeatherAspNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WeatherAspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Weather/Forcast.cshtml
@model string

@{
    ViewData["Title"] = "Forcast";
}
@section Styles {
    <link rel="stylesheet" href="~/css/weather/weather.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/weather/weatherMap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/node_modules/leaflet/dist/leaflet.css" asp-append-version="true" />
}

<div class="top-section">
    <form asp-action="Forcast">
        <div class="search">
            <div class="search-bar">
                <input placeholder="Enter city name" type="text" id="name" name="newCityName">
            </div>
            <button type="submit" class="search-btn">Search</button>

        </div>
    </form>
</div>

<div class="top-components">
    @(await Component.InvokeAsync("CityTemperature", new { newCityName = ViewData["NewCityName"]?.ToString() }))

    @(await Component.InvokeAsync("TemperatureMap"))
</div>

@section Scripts {
    <script src="~/lib/node_modules/leaflet/dist/leaflet.js" asp-append-version="true"></script>
    <script src="~/js/weatherMap/weatherMap.js" asp-append-version="true"></script>
}